<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="segurito">
  <!--  Escala del robot -->
  <xacro:property name="scale" value="1.0"/>

  <!-- Medidas adaptasdas al sistema de coordenadas de ros2-->
  <!-- 22 cm diametro-->
  <xacro:property name="base_radius" value="${0.11  * scale}"/>
  <!-- Cilindro 8.4 cm alto -->
  <xacro:property name="base_height" value="${0.084 * scale}"/>
  <!-- Cúpula: esfera radio 0.11 m -->
  <xacro:property name="dome_radius" value="${base_radius}"/>
  <!-- Altura total -->
  <xacro:property name="body_height" value="${base_height + dome_radius}"/> 
  <xacro:property name="wheel_radius" value="${0.03 * scale}"/>
  <xacro:property name="wheel_width"  value="${0.02 * scale}"/>
  <!-- Posiciones escaladas (debug ya que el robot es muy pequeño) -->
  <xacro:property name="wheel_dx" value="${-0.06 * scale}"/>
  <xacro:property name="wheel_dy" value="${ 0.0575 * scale}"/>
  <xacro:property name="wheel_cz" value="${0.005 * scale}"/>
  <xacro:property name="lidar_z" value="${0.1928 * scale}"/>
  <xacro:property name="cam_x" value="${0.0645 * scale}"/>
  <xacro:property name="cam_z" value="${0.1696 * scale}"/>
  <xacro:property name="imu_x" value="${0.08 * scale}"/>
  <xacro:property name="imu_y" value="${0.04625* scale}"/>
  <xacro:property name="imu_z" value="${0.015 * scale}"/>
   <!-- Rueda loca -->
  <xacro:property name="center_wheel_radius" value="${0.03 * scale}"/>  
  <xacro:property name="center_wheel_width"  value="${0.02 * scale}"/>   
  <xacro:property name="center_wheel_x" value="0.07"/>        
  <xacro:property name="center_wheel_y" value="0.0"/>
  <xacro:property name="center_wheel_z" value="${wheel_cz}"/> 

  <xacro:macro name="default_inertial" params="">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${1.0 * scale * scale * scale}"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- Base -->
  <link name="base_link">
    <!-- Cilindro -->
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="${base_radius}" length="${base_height}"/></geometry>
      <material name="white"><color rgba="0.8 0.8 0.8 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry><cylinder radius="${base_radius}" length="${base_height}"/></geometry>
    </collision>

    <!-- Cúpula -->
    <visual>
      <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
      <geometry><sphere radius="${dome_radius}"/></geometry>
      <material name="white"><color rgba="0.8 0.8 0.8 1"/></material>
    </visual>
    <xacro:default_inertial/>
  </link>

  <!-- Ruedas -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
        <material name="black"><color rgba="0 0 0 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
      </collision>
      <xacro:default_inertial/>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child  link="${name}_link"/>
      <origin xyz="${x} ${y} ${wheel_cz}" rpy="0 0 0"/> 
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>
  <xacro:wheel name="left_wheel"  x="${wheel_dx}"  y="${wheel_dy}"/>
  <xacro:wheel name="right_wheel" x="${wheel_dx}"  y="${-wheel_dy}"/>


  <!--  Rueda loca -->
  <link name="center_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${center_wheel_radius}" length="${center_wheel_width}"/>
      </geometry>
      <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${center_wheel_radius}" length="${center_wheel_width}"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
  </link>

  <!-- Joint pasivo (sin motor) -->
  <joint name="center_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="center_wheel_link"/>
    <origin xyz="${center_wheel_x} ${center_wheel_y} ${center_wheel_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/> 
  </joint>

  <!-- Sensor LiDAR-->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="${0.03 * scale}" length="${0.04 * scale}"/></geometry>
      <material name="black"><color rgba="0 0 1 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><cylinder radius="${0.03 * scale}" length="${0.04 * scale}"/></geometry>
    </collision>
    <xacro:default_inertial/>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="0 0 ${lidar_z}" rpy="0 0 0"/>
  </joint>

  <!-- Cámara -->
  <link name="camera_link">
    <visual>
      <geometry><box size="${0.04 * scale} ${0.04 * scale} ${0.02 * scale}"/></geometry>
      <material name="gray"><color rgba="0 1 0 1"/></material>
    </visual>
    <xacro:default_inertial/>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="camera_link"/>
    <origin xyz="${cam_x} 0 ${cam_z}" rpy="0 0.6109 0"/>
  </joint>

  <!-- Acelerómetro -->
  <link name="imu_link">
    <visual>
      <geometry><sphere radius="${0.01 * scale}"/></geometry>
      <material name="red"><color rgba="1 0 0 1"/></material>
    </visual>
    <xacro:default_inertial/>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="imu_link"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z}" rpy="0 0 0"/>
  </joint>


  <ros2_control name="SeguritoHardware" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <joint name="left_wheel_joint">
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <command_interface name="velocity"/>
    </joint>
    <joint name="right_wheel_joint">
      <state_interface name="position"/>
      <state_interface name="velocity"/>
      <command_interface name="velocity"/>
    </joint>
  </ros2_control>

  <transmission name="left_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_wheel_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_joint">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>
        /home/neverdiedooms/ros2_ws/install/segurito_description/\
  share/segurito_description/config/diff_drive.yaml
      </parameters>
    </plugin>
  </gazebo>
</robot>
