controller_manager:
  ros__parameters:
    update_rate: 50.0          # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50.0

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names:  ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]

      wheel_separation: 0.115
      wheel_radius:     0.03
      cmd_vel_timeout: 0.5
      publish_rate: 50.0
      open_loop: true
      odom_frame_id: odom
      base_frame_id: base_link
